# Generated by Django 2.2 on 2021-11-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0003_auto_20211113_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
